export type RegionId = "americas" | "europe" | "china" | "apac" | "compute";

export type LabKind = "frontier" | "open" | "infra" | "compute" | "applied";

export type Lab = {
  id: string;
  name: string;
  nameZh: string;
  city: string;
  cityZh: string;
  country: string;
  countryZh: string;
  lat: number;
  lon: number;
  region: RegionId;
  kind: LabKind;
  flagship: string;
  intel?: number;
  context?: string;
  released?: string;
  summary: string;
  highlights: string[];
};

export const REGION_LABEL: Record<RegionId | "all", string> = {
  all: "全部",
  americas: "北美",
  europe: "欧洲",
  china: "中国",
  apac: "亚太 / 中东",
  compute: "算力",
};

export const KIND_LABEL: Record<LabKind, string> = {
  frontier: "前沿",
  open: "开源权重",
  infra: "基础设施",
  compute: "训练集群",
  applied: "应用",
};

export const LABS: Lab[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    nameZh: "Anthropic",
    city: "San Francisco",
    cityZh: "旧金山",
    country: "USA",
    countryZh: "美国",
    lat: 37.776,
    lon: -122.418,
    region: "americas",
    kind: "frontier",
    flagship: "Claude Opus 5",
    intel: 63,
    context: "1M",
    released: "2026",
    summary:
      "当前公开榜单智力指数最高的实验室。Opus 5（max / xhigh）并列 Artificial Analysis Intelligence Index 63，另有 Fable 5 与 Sonnet 5 覆盖不同价位与延迟。",
    highlights: ["榜单智力指数 63", "自适应推理与努力档位", "1M 上下文"],
  },
  {
    id: "openai",
    name: "OpenAI",
    nameZh: "OpenAI",
    city: "San Francisco",
    cityZh: "旧金山",
    country: "USA",
    countryZh: "美国",
    lat: 37.798,
    lon: -122.394,
    region: "americas",
    kind: "frontier",
    flagship: "GPT-5.6 Sol",
    intel: 61,
    context: "1M",
    released: "2026",
    summary:
      "GPT-5.6 家族按档位拆分：Sol（推理）、Terra（吞吐）、Luna（低成本）。Codex 线继续服务编程代理。生态与 API 覆盖仍是最完整的之一。",
    highlights: ["Sol / Terra / Luna 三线", "1M 上下文", "编程代理 Codex"],
  },
  {
    id: "spacexai",
    name: "SpaceXAI",
    nameZh: "SpaceXAI",
    city: "Bay Area",
    cityZh: "湾区",
    country: "USA",
    countryZh: "美国",
    lat: 37.442,
    lon: -122.162,
    region: "americas",
    kind: "frontier",
    flagship: "Grok 4.6",
    intel: 61,
    context: "500k",
    released: "2026-08-12",
    summary:
      "原 xAI。Grok 4.6 于 2026 年 8 月 12 日发布，覆盖推理、代码、语音与图像/视频生成，并进入 GitHub Copilot。训练主要在孟菲斯 Colossus 集群完成。",
    highlights: ["2026.8.12 发布 Grok 4.6", "实时检索 X", "GitHub Copilot 接入"],
  },
  {
    id: "google-mv",
    name: "Google DeepMind",
    nameZh: "Google DeepMind",
    city: "Mountain View",
    cityZh: "山景城",
    country: "USA",
    countryZh: "美国",
    lat: 37.422,
    lon: -122.084,
    region: "americas",
    kind: "frontier",
    flagship: "Gemini 3.7 Flash",
    intel: 56,
    context: "1M",
    released: "2026",
    summary:
      "Gemini 3.7 Flash 是目前最快的前沿档之一，约 320 tok/s，延迟极低。Pro / Deep Think 线负责重推理，Gemma 4 提供开源侧。",
    highlights: ["约 320 tok/s", "1M 上下文", "搜索与 Workspace 原生集成"],
  },
  {
    id: "meta",
    name: "Meta",
    nameZh: "Meta",
    city: "Menlo Park",
    cityZh: "门洛帕克",
    country: "USA",
    countryZh: "美国",
    lat: 37.485,
    lon: -122.148,
    region: "americas",
    kind: "open",
    flagship: "Muse Spark 1.2",
    intel: 57,
    context: "1.05M",
    released: "2026",
    summary:
      "超智能实验室同时推进开源 Llama 4（Scout 10M 上下文、Maverick）与 Muse Spark 前沿线。开源权重仍是全球微调生态的底座。",
    highlights: ["Llama 4 Scout 10M 上下文", "Muse Spark 智力指数 57", "开源生态最大"],
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    nameZh: "NVIDIA",
    city: "Santa Clara",
    cityZh: "圣克拉拉",
    country: "USA",
    countryZh: "美国",
    lat: 37.371,
    lon: -121.967,
    region: "americas",
    kind: "infra",
    flagship: "Nemotron / CUDA",
    summary:
      "几乎所有前沿训练都跑在 NVIDIA 集群上。Nemotron 开源模型、CUDA 与 Blackwell 系统决定了 2026 年的算力上限与推理单价。",
    highlights: ["训练与推理算力底座", "Nemotron 开源系列", "Blackwell 系统"],
  },
  {
    id: "apple",
    name: "Apple",
    nameZh: "Apple",
    city: "Cupertino",
    cityZh: "库比蒂诺",
    country: "USA",
    countryZh: "美国",
    lat: 37.335,
    lon: -122.009,
    region: "americas",
    kind: "applied",
    flagship: "Apple Intelligence",
    summary:
      "端侧优先：设备上的基础模型处理隐私敏感任务，云端大模型走 Private Cloud Compute。不追逐公开榜单，而是把模型嵌进系统。",
    highlights: ["端侧优先", "Private Cloud Compute", "系统级集成"],
  },
  {
    id: "microsoft",
    name: "Microsoft",
    nameZh: "Microsoft",
    city: "Redmond",
    cityZh: "雷德蒙德",
    country: "USA",
    countryZh: "美国",
    lat: 47.642,
    lon: -122.137,
    region: "americas",
    kind: "applied",
    flagship: "Copilot / Azure AI",
    summary:
      "把 OpenAI 与自研 MAI 模型铺进 Office、GitHub、Windows 与 Azure。企业分发与合规通道，而不只是聊天入口。",
    highlights: ["GitHub Copilot", "Azure 模型目录", "Office 全线"],
  },
  {
    id: "amazon",
    name: "Amazon",
    nameZh: "Amazon",
    city: "Seattle",
    cityZh: "西雅图",
    country: "USA",
    countryZh: "美国",
    lat: 47.616,
    lon: -122.339,
    region: "americas",
    kind: "applied",
    flagship: "Bedrock / Nova",
    summary:
      "Bedrock 聚合多家模型；Nova 是自研多模态线。AWS 把推理做成按 token 计费的云服务，是企业落地的默认通道之一。",
    highlights: ["Bedrock 多模型", "Nova 多模态", "AWS 全球推理"],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    nameZh: "Perplexity",
    city: "San Francisco",
    cityZh: "旧金山",
    country: "USA",
    countryZh: "美国",
    lat: 37.791,
    lon: -122.401,
    region: "americas",
    kind: "applied",
    flagship: "Sonar",
    summary:
      "以检索增强回答搜索。自研 Sonar 叠加多家前沿模型，产品形态是答案引擎而不是通用聊天。",
    highlights: ["答案引擎", "实时检索", "Sonar API"],
  },
  {
    id: "colossus",
    name: "Colossus",
    nameZh: "Colossus 集群",
    city: "Memphis",
    cityZh: "孟菲斯",
    country: "USA",
    countryZh: "美国",
    lat: 35.149,
    lon: -90.049,
    region: "compute",
    kind: "compute",
    flagship: "Grok 训练超算",
    released: "2024–2026",
    summary:
      "SpaceXAI 在孟菲斯 / 绍斯黑文的训练工厂。从废弃工厂 122 天拉起，再扩到约 20 万 H100，并继续向 GW 级与百万 GPU 目标推进。Anthropic 也曾租用部分算力。",
    highlights: ["全球最大单一训练集群之一", "122 天建成", "Grok 4.x 训练地"],
  },
  {
    id: "deepmind-london",
    name: "Google DeepMind",
    nameZh: "DeepMind 伦敦",
    city: "London",
    cityZh: "伦敦",
    country: "UK",
    countryZh: "英国",
    lat: 51.533,
    lon: -0.126,
    region: "europe",
    kind: "frontier",
    flagship: "Gemini / Gemma 4",
    context: "1M",
    summary:
      "DeepMind 起源地。研究仍高度集中在伦敦：强化学习、科学模型与 Gemma 开源权重从这里走向全球。",
    highlights: ["DeepMind 总部", "Gemma 4 开源", "科学与智能体研究"],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    nameZh: "Mistral AI",
    city: "Paris",
    cityZh: "巴黎",
    country: "France",
    countryZh: "法国",
    lat: 48.875,
    lon: 2.326,
    region: "europe",
    kind: "open",
    flagship: "Mistral Large",
    summary:
      "欧洲最重要的前沿实验室。开源 Mixtral / Small 与商业 Large 并行，强调主权部署与欧盟合规，是美国实验室之外最完整的替代栈。",
    highlights: ["欧洲前沿", "开源 + 商业双线", "主权云部署"],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    nameZh: "Hugging Face",
    city: "Paris / NYC",
    cityZh: "巴黎 / 纽约",
    country: "France",
    countryZh: "法国",
    lat: 48.834,
    lon: 2.371,
    region: "europe",
    kind: "infra",
    flagship: "Hub / Inference",
    summary:
      "开源模型的港口。几乎所有可下载权重、评测空间与推理 endpoint 都经过 Hub。不训练最大模型，但决定模型如何流通。",
    highlights: ["模型 Hub", "开源分发", "Inference Endpoints"],
  },
  {
    id: "cohere",
    name: "Cohere",
    nameZh: "Cohere",
    city: "Toronto",
    cityZh: "多伦多",
    country: "Canada",
    countryZh: "加拿大",
    lat: 43.653,
    lon: -79.383,
    region: "americas",
    kind: "applied",
    flagship: "Command",
    summary:
      "企业检索与代理。Command 系列针对 RAG、工具调用与私有部署，客户是银行、政府和咨询公司而不是消费者聊天。",
    highlights: ["企业 RAG", "Command 系列", "私有部署"],
  },
  {
    id: "runway",
    name: "Runway",
    nameZh: "Runway",
    city: "New York",
    cityZh: "纽约",
    country: "USA",
    countryZh: "美国",
    lat: 40.721,
    lon: -73.997,
    region: "americas",
    kind: "applied",
    flagship: "Gen-4",
    summary:
      "视频生成的产品实验室。Gen-4 面向电影与广告工作流，是好莱坞管道里最常用的生成视频工具之一。",
    highlights: ["Gen-4 视频", "影视工作流", "多模态生成"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    nameZh: "深度求索",
    city: "Hangzhou",
    cityZh: "杭州",
    country: "China",
    countryZh: "中国",
    lat: 30.274,
    lon: 120.155,
    region: "china",
    kind: "open",
    flagship: "DeepSeek V4",
    intel: 53,
    context: "1M",
    released: "2026",
    summary:
      "开源权重效率的标尺。V4 / V4-Flash 在公开评测里以极低单价接近前沿，Flash 被研究机构称为知名模型里最便宜的一档。",
    highlights: ["开源权重", "V4-Flash 极低单价", "1M 上下文"],
  },
  {
    id: "qwen",
    name: "Alibaba Qwen",
    nameZh: "阿里通义千问",
    city: "Hangzhou",
    cityZh: "杭州",
    country: "China",
    countryZh: "中国",
    lat: 30.189,
    lon: 120.19,
    region: "china",
    kind: "open",
    flagship: "Qwen3.8 Max",
    intel: 58,
    context: "1M",
    released: "2026-08-03",
    summary:
      "2026 年 8 月 3 日发布 Qwen3.8-Max，约 2.4 万亿参数，接近月之暗面 Kimi K3 的规模。开源与商业 API 并行，是中文生态使用最广的底座之一。",
    highlights: ["2.4T 参数", "智力指数 58", "中文生态底座"],
  },
  {
    id: "moonshot",
    name: "Moonshot AI",
    nameZh: "月之暗面",
    city: "Beijing",
    cityZh: "北京",
    country: "China",
    countryZh: "中国",
    lat: 39.992,
    lon: 116.327,
    region: "china",
    kind: "open",
    flagship: "Kimi K3",
    intel: 60,
    context: "1.05M",
    released: "2026-07",
    summary:
      "Kimi K3 约 2.8 万亿参数，智力指数 60，长上下文与代理能力是产品标签。Kimi 聊天在中文用户里渗透极高。",
    highlights: ["2.8T 参数", "智力指数 60", "超长上下文"],
  },
  {
    id: "zhipu",
    name: "Zhipu AI",
    nameZh: "智谱",
    city: "Beijing",
    cityZh: "北京",
    country: "China",
    countryZh: "中国",
    lat: 39.959,
    lon: 116.298,
    region: "china",
    kind: "open",
    flagship: "GLM-5.3",
    intel: 60,
    context: "1M",
    released: "2026",
    summary:
      "GLM-5.3（max）智力指数 60，推理速度快、单价低，是国内 API 里性价比最高的一档之一。清华背景，企业与开源双轮。",
    highlights: ["智力指数 60", "高吞吐低单价", "清华系"],
  },
  {
    id: "bytedance",
    name: "ByteDance Seed",
    nameZh: "字节跳动 Seed",
    city: "Beijing",
    cityZh: "北京",
    country: "China",
    countryZh: "中国",
    lat: 39.997,
    lon: 116.481,
    region: "china",
    kind: "applied",
    flagship: "Doubao / Seed",
    summary:
      "豆包是中国用户规模最大的消费级助手之一。Seed 研究线做基础模型，产品则嵌进抖音、飞书与火山引擎。",
    highlights: ["豆包用户规模", "火山引擎", "消费级分发"],
  },
  {
    id: "minimax",
    name: "MiniMax",
    nameZh: "MiniMax",
    city: "Shanghai",
    cityZh: "上海",
    country: "China",
    countryZh: "中国",
    lat: 31.23,
    lon: 121.474,
    region: "china",
    kind: "applied",
    flagship: "Hailuo / M 系列",
    summary:
      "上海实验室，语音与视频生成是长板。Hailuo 视频与 M 系列文本模型并行，面向创作者与出海 API。",
    highlights: ["Hailuo 视频", "语音合成", "出海 API"],
  },
  {
    id: "tencent",
    name: "Tencent",
    nameZh: "腾讯混元",
    city: "Shenzhen",
    cityZh: "深圳",
    country: "China",
    countryZh: "中国",
    lat: 22.541,
    lon: 113.935,
    region: "china",
    kind: "applied",
    flagship: "Hunyuan",
    summary:
      "混元模型服务微信、QQ 与腾讯云。优势是分发：十亿级日活入口，而不是公开榜单名次。",
    highlights: ["微信入口", "腾讯云", "混元多模态"],
  },
  {
    id: "g42",
    name: "G42 / TII",
    nameZh: "G42 / 技术创新研究所",
    city: "Abu Dhabi",
    cityZh: "阿布扎比",
    country: "UAE",
    countryZh: "阿联酋",
    lat: 24.454,
    lon: 54.377,
    region: "apac",
    kind: "open",
    flagship: "Falcon",
    summary:
      "海湾主权 AI。Falcon 开源系列与超算集群让阿联酋成为美国、中国之外的第三极算力与模型来源。",
    highlights: ["Falcon 开源", "主权模型", "海湾超算"],
  },
  {
    id: "sakana",
    name: "Sakana AI",
    nameZh: "Sakana AI",
    city: "Tokyo",
    cityZh: "东京",
    country: "Japan",
    countryZh: "日本",
    lat: 35.676,
    lon: 139.65,
    region: "apac",
    kind: "frontier",
    flagship: "Evolutionary models",
    summary:
      "东京研究实验室，用演化算法与自然计算思路做模型合并与高效智能。体量不大，方向独特。",
    highlights: ["演化模型合并", "东京研究", "高效智能"],
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    nameZh: "AI21 Labs",
    city: "Tel Aviv",
    cityZh: "特拉维夫",
    country: "Israel",
    countryZh: "以色列",
    lat: 32.085,
    lon: 34.782,
    region: "apac",
    kind: "open",
    flagship: "Jamba",
    summary:
      "Jamba 把 SSM 与 Transformer 做成混合架构，长上下文成本低于纯注意力模型。特拉维夫是中东除海湾外最密集的模型团队之一。",
    highlights: ["SSM × Transformer", "长上下文效率", "特拉维夫"],
  },
];

export const REGIONS: Array<RegionId | "all"> = [
  "all",
  "americas",
  "europe",
  "china",
  "apac",
  "compute",
];

export function getLab(id: string | null): Lab | undefined {
  if (!id) return undefined;
  return LABS.find((l) => l.id === id);
}

export function labsInRegion(region: RegionId | "all"): Lab[] {
  if (region === "all") return LABS;
  return LABS.filter((l) => l.region === region);
}
